services:
  mysql:
    image: mysql:8.0
    container_name: collection_mysql
    restart: always
    env_file:
      - ./.env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./app/backend
    container_name: collection_backend
    ports:
      - "${BACKEND_PORT}:5000"
    env_file:
      - ./.env
    depends_on:
      - mysql

  frontend:
    build: ./app/frontend
    container_name: collection_frontend
    ports:
      - "${FRONTEND_PORT}:5173"
    depends_on:
      - backend

  caddy:
    image: caddy:2
    container_name: collection_caddy
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - frontend
      - backend

volumes:
  mysql_data:
