services:
  backend:
    build: ./backend
    container_name: collection_backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    container_name: collection_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  mysql:
    image: mysql:8.0
    container_name: collection_mysql
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  caddy:
    image: caddy:2
    container_name: collection_caddy
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - frontend
      - backend

volumes:
  mysql_data:
  caddy_data:
  caddy_config:
